apiVersion: v2
name: account-debit-svc
version: 0.0.1
appVersion: 1.0.0

dependencies:
  - name: app-library-chart
  #- name: stackrox-central-services
    version: v2
    #version: 61.1.0
    #repository: https://mirror.openshift.com/pub/rhacs/charts/
    repository: http://nexus.apps.kechung.tamlab.rdu2.redhat.com/service/rest/repository/browse/hosted-helm/
    #repository: file://../app-library-chart
